"""Agent context pack generation."""

from __future__ import annotations

import json
from pathlib import Path

from omnivorous.agents import AgentTarget, resolve_agents
from omnivorous.frontmatter import add_frontmatter
from omnivorous.models import DocumentMetadata
from omnivorous.pipeline import (
    discover_source_files,
    iter_converted_documents,
    resolve_output_paths as pipeline_resolve_output_paths,
)
from omnivorous.registry import ensure_registry_loaded


def generate_agent_instructions(
    docs_metadata: list[DocumentMetadata], agent: AgentTarget
) -> str:
    """Generate an instruction file for the given agent target."""
    lines = [
        "# Project Context",
        "",
        "This directory contains documentation converted by omnivorous for use as AI agent context.",
        "",
        "## Available Documents",
        "",
    ]
    for meta in docs_metadata:
        lines.append(f"- **{meta.title}** (~{meta.tokens_estimate} tokens)")

    lines.extend([
        "",
        "## Usage",
        "",
        "Read the documents in `docs/` for project context. "
        "See `manifest.json` for a full listing.",
        "",
        f"Generated by omnivorous for {agent.display_name}.",
    ])
    return "\n".join(lines) + "\n"


def generate_claude_md(docs_metadata: list[DocumentMetadata]) -> str:
    """Generate a CLAUDE.md file with agent instructions. Kept for backward compatibility."""
    from omnivorous.agents import AGENT_TARGETS

    return generate_agent_instructions(docs_metadata, AGENT_TARGETS["claude"])


def generate_project_context(docs_metadata: list[DocumentMetadata]) -> str:
    """Generate a PROJECT_CONTEXT.md summary."""
    lines = [
        "# Project Documentation Summary",
        "",
        f"Total documents: {len(docs_metadata)}",
        f"Total estimated tokens: {sum(m.tokens_estimate for m in docs_metadata)}",
        "",
        "## Documents",
        "",
    ]
    for meta in docs_metadata:
        lines.append(f"### {meta.title}")
        lines.append(f"- Source: `{meta.source}`")
        if meta.pages:
            lines.append(f"- Pages: {meta.pages}")
        if meta.headings:
            lines.append(f"- Headings: {len(meta.headings)}")
        if meta.tables:
            lines.append(f"- Tables: {meta.tables}")
        if meta.images:
            lines.append(f"- Images: {meta.images}")
        lines.append(f"- Tokens: {meta.tokens_estimate}")
        lines.append("")

    return "\n".join(lines)


def generate_manifest(
    docs_metadata: list[DocumentMetadata],
    output_files: list[str],
    original_sources: list[str] | None = None,
) -> str:
    """Generate a manifest.json for the agent context pack."""
    documents = []
    for i, m in enumerate(docs_metadata):
        doc = m.to_dict()
        if original_sources and i < len(original_sources):
            doc["original_source"] = original_sources[i]
        documents.append(doc)
    manifest = {
        "version": "1.0",
        "generator": "omnivorous",
        "documents": documents,
        "output_files": output_files,
        "total_tokens": sum(m.tokens_estimate for m in docs_metadata),
    }
    return json.dumps(manifest, indent=2) + "\n"


def resolve_output_paths(
    source_files: list[Path], source_dir: Path
) -> dict[Path, Path]:
    """Backward-compatible wrapper for the shared output path resolver."""
    return pipeline_resolve_output_paths(source_files, source_dir)


def pack_context(
    source_dir: Path,
    output_dir: Path,
    agents: list[str] | None = None,
) -> Path:
    """Orchestrate full pipeline: convert all docs and generate agent context pack."""
    ensure_registry_loaded()
    docs_dir = output_dir / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    # Find and convert all supported files
    source_files = discover_source_files(source_dir)

    output_map = resolve_output_paths(source_files, source_dir)
    all_metadata: list[DocumentMetadata | None] = [None] * len(source_files)
    doc_output_files: list[str] = [""] * len(source_files)
    original_sources: list[str] = [""] * len(source_files)

    for index, source_file, result in iter_converted_documents(source_files):
        # Save original source as relative path before overwriting
        original_sources[index] = source_file.relative_to(source_dir).as_posix()

        # Point source to the output markdown so agents read the converted file
        out_rel = output_map[source_file]
        result.metadata.source = f"docs/{out_rel.as_posix()}"
        md_with_frontmatter = add_frontmatter(result.content, result.metadata.to_dict())
        out_path = docs_dir / out_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(md_with_frontmatter, encoding="utf-8")
        all_metadata[index] = result.metadata
        doc_output_files[index] = f"docs/{out_rel.as_posix()}"

    # Generate meta files
    all_metadata = [meta for meta in all_metadata if meta is not None]
    all_output_files = [path for path in doc_output_files if path]
    original_sources = [source for source in original_sources if source]

    resolved = resolve_agents(agents or ["claude"])
    for agent in resolved:
        instructions = generate_agent_instructions(all_metadata, agent)
        agent_path = output_dir / agent.file_path
        agent_path.parent.mkdir(parents=True, exist_ok=True)
        agent_path.write_text(instructions, encoding="utf-8")
        all_output_files.append(agent.file_path)

    project_ctx = generate_project_context(all_metadata)
    (output_dir / "PROJECT_CONTEXT.md").write_text(project_ctx, encoding="utf-8")
    all_output_files.append("PROJECT_CONTEXT.md")

    all_output_files.append("manifest.json")
    manifest = generate_manifest(all_metadata, all_output_files, original_sources)
    (output_dir / "manifest.json").write_text(manifest, encoding="utf-8")

    return output_dir
